apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confluence-credentials
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: confluence-credentials
    creationPolicy: Owner
  data:
    - secretKey: CONFLUENCE_TOKEN
      remoteRef:
        key: secrets/rhdh/confluence-credentials
        property: value
